server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /1/ {
        proxy_pass http://flask1:5000/;
    }
    location /2/ {
        proxy_pass http://flask2:5000/;
    }
    location /3/ {
        proxy_pass http://flask3:5000/;
    }
}