apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: global-efs
  resources:
    requests:
      storage: 500Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
spec:
  containers:
  - name: efs-pod
    image: ubuntu:24.04
    command:
    - sh
    - -c
    args:
    - sleep infinity
    volumeMounts:
    - name: efs-storage
      mountPath: /shared
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs