apiVersion: v1
kind: Pod
metadata:
  name: task-04
spec:
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        memory: 3Gi
        cpu: 3000m
      limits:
        memory: 3Gi
        cpu: 3000m