apiVersion: v1
kind: Secret
metadata:
  name: secret-1
data:
  NAME: aGF5YWdyZWV2YW4K
  VERSION: My4wCg==

---
# k create configmap config-2 --from-file=task_03-config.properties
---
apiVersion: v1
kind: Pod
metadata:
  name: task-02
spec:
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: NAME
      valueFrom:
        secretKeyRef:
          name: secret-1
          key: NAME
    volumeMounts:
    - name: secrets
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: secret-1
